import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode}) {

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}>
          <div className="flex">
            <Sidebar />
            <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
